routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});



Auth::routes();
Route::middleware('auth')->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('prodi', 'ProdiController');
    Route::resource('bidang-ilmu', 'BidangIlmuController');
    Route::resource('dosen', 'DosenController');
    Route::resource('kompetensi', 'KompetensiController');
    Route::resource('almamater', 'AlmamaterController');
    Route::resource('user', 'UserController');

    // kompetensi dosen
    Route::get('dosen/{id}/kompetensi-dosen', 'KompetensiDosenController@index')->name('kompetensi-dosen.index');
    Route::post('dosen/{id}/kompetensi-dosen', 'KompetensiDosenController@store')->name('kompetensi-dosen.store');
    Route::delete('dosen/{id}/kompetensi-dosen/{dosen_id}', 'KompetensiDosenController@delete')->name('kompetensi-dosen.destroy');
    //end kompetensi dosen

    //pendidikan dosen
    Route::get('dosen/{id}/pendidikan', 'PendidikanController@index')->name('pendidikan.index');
    Route::get('dosen/{id}/pendidikan/create', 'PendidikanController@create')->name('pendidikan.create');
    Route::post('dosen/{id}/pendidikan/create', 'PendidikanController@store')->name('pendidikan.store');
    Route::delete('dosen/{id}/pendidikan', 'PendidikanController@delete')->name('pendidikan.destroy');
    Route::get('pendidikan/{penidikan_id}/edit', 'PendidikanController@edit')->name('pendidikan.edit');
    Route::put('pendidikan/{pendidikan_id}/update', 'PendidikanController@update')->name('pendidikan.update');
    //end pendidikan dosen

    //jabatan fungsional
    Route::get('dosen/{id}/jabatan-fungsional', 'JabatanFungsionalController@indexDosen')->name('jabatan-fungsional.indexDosen');
    Route::get('dosen/{id}/jabatan-fungsional/create', 'JabatanFungsionalController@create')->name('jabatan-fungsional.create');
    Route::post('jabatan-fungsional/store', 'JabatanFungsionalController@store')->name('jabatan-fungsional.store');
    Route::get('jabatan-fungsional/{jabatan_id}/edit', 'JabatanFungsionalController@edit')->name('jabatan-fungsional.edit');
    Route::put('jabatan-fungsional/{jabatan_id}/update', 'JabatanFungsionalController@update')->name('jabatan-fungsional.update');
    Route::delete('jabatan-fungsional/{id}/delete', 'JabatanFungsionalController@delete')->name('jabatan-fungsional.destroy');
    Route::get('jabatan-fungsional', 'JabatanFungsionalController@index')->name('jabatan-fungsional.index');
    //end jabatan fungsional 

    //diklat
    Route::get('dosen/{dosen_id}/diklat', 'DiklatController@indexDosen')->name('diklat.indexDosen');
    Route::get('dosen/{dosen_id}/diklat/create', 'DiklatController@create')->name('diklat.create');
    Route::post('diklat/store', 'DiklatController@store')->name('diklat.store');
    Route::delete('diklat/{id}/delete', 'DiklatController@destroy')->name('diklat.destroy');
    Route::get('diklat/{id}/edit', 'DiklatController@edit')->name('diklat.edit');
    Route::PUT('diklat/{id}/update', 'DiklatController@update')->name('diklat.update');
    Route::get('diklat', 'DiklatController@index')->name('diklat.index');
    //end diklat

    //Penelitian pengabdian
    Route::get('dosen/{dosen_id}/penelitian-pengabdian', 'PenelitianPengabdianController@indexDosen')->name('penelitian-pengabdian.indexDosen');
    Route::get('dosen/{dosen_id}/penelitian-pengabdian/create', 'PenelitianPengabdianController@create')->name('penelitian-pengabdian.create');
    Route::post('penelitian-pengabdian/store', 'PenelitianPengabdianController@store')->name('penelitian-pengabdian.store');
    Route::delete('penelitian-pengabdian/{id}/delete', 'PenelitianPengabdianController@destroy')->name('penelitian-pengabdian.destroy');
    Route::get('penelitian-pengabdian/{id}/edit', 'PenelitianPengabdianController@edit')->name('penelitian-pengabdian.edit');
    Route::PUT('penelitian-pengabdian/{id}/update', 'PenelitianPengabdianController@update')->name('penelitian-pengabdian.update');
    Route::get('penelitian-pengabdian', 'PenelitianPengabdianController@index')->name('penelitian-pengabdian.index');
    //end penelitian pengabdian


    //pengajaran
    Route::resource('dosen/{dosen_id}/pengajaran', 'PengajaranController');
    Route::get('pengajaran', 'PengajaranController@indexAll')->name('pengajaran');
    //end pengajaran

    //sertifikasi
    Route::resource('dosen/{dosen_id}/sertifikasi', 'SertifikasiController');
    Route::get('sertifikasi', 'SertifikasiController@indexAll')->name('sertifikasi');
    //endsertifikasi

    //dosen prodi
    Route::get('prodi/{prodi_id}/dosen', 'ProdiController@dosen')->name('prodi.dosen');
    //end dosen prodi

    //dosen bidang ilmu
    Route::get('bidang-ilmu/{bidang_id}/dosen', 'BidangIlmuController@dosen')->name('bidang-ilmu.dosen');
    //end bidang ilmu

     //dosen prodi
     Route::get('almamater/{almamater_id}/dosen', 'AlmamaterController@dosen')->name('almamater.dosen');
     //end dosen prodi

     //dosen prodi
     Route::get('kompetensi/{kompetensi_id}/dosen', 'KompetensiController@dosen')->name('kompetensi.dosen');
     //end dosen prodi


     //print pdf
     Route::get('print-dosen', 'PdfController@dosen')->name('dosen.print');
     Route::get('print-dosen-prodi/{id}', 'PdfController@dosenProdi')->name('print.dosen-prodi');
     //excell
     Route::get('export-dosen', 'ExcelController@exportDosen')->name('export.dosen');
     Route::get('export-dosen-prodi/{id}', 'ExcelController@exportDosenProdi')->name('export.dosen-prodi');
});

app/BidangIlmu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BidangIlmu extends Model
{
    protected $fillable = [
        'kode',
        'nama_bidang_ilmu',
        'level',
        'parent_code',
        'deskripsi',
    ];

    protected $table = 'rumpun_bidang_ilmu';

    public function dosen(){
        return $this->hasMany('App\Dosen');
    }
}

app/Http/Controllers/BidangIlmuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\BidangIlmu;
use App\Dosen;
use App\User;
use Illuminate\Support\Facades\Auth;

class BidangIlmuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    public function __construct(){
        $this->middleware('kaprodi', ['only' => ['create', 'edit', 'destroy']]);
    }

    public function index()
    {
        if(isset($_GET['type'])){
            $bidang_ilmu = BidangIlmu::has('dosen')->get();           
        } else {
            $bidang_ilmu = BidangIlmu::all();
        }
        return view('bidang_ilmu.index')->with('bidang_ilmu', $bidang_ilmu);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function create()
    // {   
    //     return view ('bidang_ilmu.create');
    // }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    // public function store(Request $request)
    // {
    //     $this->validate($request, [
    //         'nama_bidang_ilmu' => 'required|unique:rumpun_bidang_ilmu',
    //         'level' => 'required|numeric'
    //     ]);

    //     BidangIlmu::create($request->all());

    //     return redirect()->route('bidang-ilmu.index')->with('success', 'Berhasil menambah data rumpun bidang ilmu');
    // }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function edit($id)
    // {
    //     $data['bidang_ilmu'] = BidangIlmu::find($id);
    //     return view('bidang_ilmu.edit', $data);
    // }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function update(Request $request, $id)
    // {
    //     $this->validate($request, [
    //         'nama_bidang_ilmu' => 'required',
    //         'level' => 'required|numeric'
    //     ]);
    //     BidangIlmu::find($id)->update($request->all());
    //     return redirect()->route('bidang-ilmu.index')->with('success', 'Berhasil mengedit data rumpun bidang ilmu');
    // }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function destroy($id)
    // {
    //     BidangIlmu::findOrFail($id)->delete();
    //     return redirect()->route('bidang-ilmu.index')->with('success', 'Berhasil menghapus data rumpun bidang ilmu');
    // }


    public function dosen($id)
    {
        $bidang_ilmu = BidangIlmu::findOrFail($id);
        $dosen = $bidang_ilmu->dosen()->orderBy('nama', 'asc')->get();
        
        return view('bidang_ilmu.dosen')->with(['bidang_ilmu' => $bidang_ilmu, 'dosen' => $dosen]);
    }


    public function getLevelRumpun(Request $request)
    {
        
        $rumpun = BidangIlmu::where('parent_code', $request->parent_code)->get();
        return response()->json($rumpun);
    }
}

resources/views/bidang_ilmu/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Bidang Ilmu')

@section('content')

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Tambah Rumpun Bidang Ilmu</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('bidang-ilmu.store') }}" method="post">
                    @csrf
                    <div class="form-group">       
                        <label>Nama Bidang Ilmu</label>
                        <input type="text" placeholder="Masukan Nama Bidang Ilmu" class="form-control" name="nama_bidang_ilmu" value="{{ old('nama_bidang_ilmu') }}">
                    </div>  
                    <div class="form-group">
                        <label>Deskripsi</label>
                        <textarea name="deskripsi" class="form-control" placeholder="Masukan Deskripsi">{{ old('deskripsi') }}</textarea>
                    </div>
                    <div class="form-group">
                        <label>Level</label>
                        <select name="level" class="form-control">
                            <option value=""> - Pilih Level - </option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>                  
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/bidang_ilmu/dosen.blade.php
@extends('layouts.app')

@section('title')
Dosen Bidang Ilmu {{ $bidang_ilmu->nama_bidang_ilmu }}
@endsection


@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Dosen Pada Bidang Ilmu {{ $bidang_ilmu->nama_bidang_ilmu }}</h4>
            </div>
            <div class="card-body mt-3">                
                <table class="table table-sm table-striped datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>NIDN</th>
                            <th>Nama</th>
                            <th>Bidang Ilmu</th>
                            <th>Prodi</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($dosen as $row)                        
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $row->nidn }}</td>
                            <td>{{ $row->nama }}</td>
                            <td>{{ $row->bidangIlmu->nama_bidang_ilmu }}</td>
                            <td>{{ $row->prodi->nama_prodi }}</td>
                            <td>
                                <a href="{{ route('dosen.show', $row->id) }}" class="text-info" title="Lihat Info Dosen"><i class="fa fa-address-card"></i></a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/bidang_ilmu/edit.blade.php
@extends('layouts.app')

@section('title', 'Program Studi')

@section('content')

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Edit Rumpun Bidang Ilmu</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('bidang-ilmu.update', $bidang_ilmu->id) }}" method="post">
                    @csrf
                    @method('put')
                    <div class="form-group">       
                        <label>Nama Bidang Ilmu</label>
                        <input type="text" placeholder="Masukan Nama Bidang Ilmu" class="form-control" name="nama_bidang_ilmu" value="{{ $bidang_ilmu->nama_bidang_ilmu }}">
                    </div>  
                    <div class="form-group">
                        <label>Deskripsi</label>
                        <textarea name="deskripsi" class="form-control" placeholder="Masukan Deskripsi">{{ $bidang_ilmu->deskripsi }}</textarea>
                    </div>
                    <div class="form-group">
                        <label>Level</label>
                        <select name="level" class="form-control">
                            <option value=""> - Pilih Level - </option>
                            <option value="1" {{ ($bidang_ilmu->level == 1) ? 'selected' : '' }}>1</option>
                            <option value="2" {{ ($bidang_ilmu->level == 2) ? 'selected' : '' }}>2</option>
                            <option value="3" {{ ($bidang_ilmu->level == 3) ? 'selected' : '' }}>3</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>                  
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/bidang_ilmu/index.blade.php
@extends('layouts.app')

@section('title', 'Program Studi')

@section('content')


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Rumpun Bidang Ilmu</h4>
            </div>
            <div class="card-body">

                <div class="row mb-3">
                    <div class="col-md-7">
                        <div class="form-group">
                            <select name="rumpun" id="show_rumpun" class="form-control">
                                <option value="1">Tampilkan seluruh rumpun bidang ilmu</option>
                                <option value="0" {{ (isset($_GET['type'])) ? 'selected' : '' }} >Tampilkan rumpun bidang ilmu yang dimiliki oleh dosen di STIKOM Bali</option>
                            </select>
                        </div>
                    </div>
                </div>
                
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Kode</th>
                            <th>Nama Bidang Ilmu</th>                
                            <th class="text-center">Level</th>                       
                            <th class="text-center">Dosen</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($bidang_ilmu as $row)
                       <tr class="{{ isRumpunLevel($row->level) }} ">
                           <td>{{ $loop->iteration }}</td>
                           <td>{{ $row->kode }}</td>
                           <td>{{ $row->nama_bidang_ilmu }}</td>                   
                           <td class="text-center">{{ $row->level }}</td>
                           <td class="text-center">
                               @if($row->level != 3)
                                -
                               @else 
                                
                                <a href="{{ route('bidang-ilmu.dosen', $row->id) }}" class="text-primary" title="Lihat dosen bidang ilmu ini"><i class="fa fa-user-tie"></i></a>
                               
                                @endif
                           </td>
                       </tr>
                       @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection


@push('scripts')

<script>

$(document).ready(function(){
    $('#show_rumpun').change(function(){
        if($('#show_rumpun').val() == 1){
            window.location = "{{ route('bidang-ilmu.index') }}";
        } else {
            window.location = "{{ route('bidang-ilmu.index', ['type' => 'all' ]) }}";
        }
    });
});

</script>

@endpush