routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});



Auth::routes();
Route::middleware('auth')->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('prodi', 'ProdiController');
    Route::resource('bidang-ilmu', 'BidangIlmuController');
    Route::resource('dosen', 'DosenController');
    Route::resource('kompetensi', 'KompetensiController');
    Route::resource('almamater', 'AlmamaterController');
    Route::resource('user', 'UserController');

    // kompetensi dosen
    Route::get('dosen/{id}/kompetensi-dosen', 'KompetensiDosenController@index')->name('kompetensi-dosen.index');
    Route::post('dosen/{id}/kompetensi-dosen', 'KompetensiDosenController@store')->name('kompetensi-dosen.store');
    Route::delete('dosen/{id}/kompetensi-dosen/{dosen_id}', 'KompetensiDosenController@delete')->name('kompetensi-dosen.destroy');
    //end kompetensi dosen

    //pendidikan dosen
    Route::get('dosen/{id}/pendidikan', 'PendidikanController@index')->name('pendidikan.index');
    Route::get('dosen/{id}/pendidikan/create', 'PendidikanController@create')->name('pendidikan.create');
    Route::post('dosen/{id}/pendidikan/create', 'PendidikanController@store')->name('pendidikan.store');
    Route::delete('dosen/{id}/pendidikan', 'PendidikanController@delete')->name('pendidikan.destroy');
    Route::get('pendidikan/{penidikan_id}/edit', 'PendidikanController@edit')->name('pendidikan.edit');
    Route::put('pendidikan/{pendidikan_id}/update', 'PendidikanController@update')->name('pendidikan.update');
    //end pendidikan dosen

    //jabatan fungsional
    Route::get('dosen/{id}/jabatan-fungsional', 'JabatanFungsionalController@indexDosen')->name('jabatan-fungsional.indexDosen');
    Route::get('dosen/{id}/jabatan-fungsional/create', 'JabatanFungsionalController@create')->name('jabatan-fungsional.create');
    Route::post('jabatan-fungsional/store', 'JabatanFungsionalController@store')->name('jabatan-fungsional.store');
    Route::get('jabatan-fungsional/{jabatan_id}/edit', 'JabatanFungsionalController@edit')->name('jabatan-fungsional.edit');
    Route::put('jabatan-fungsional/{jabatan_id}/update', 'JabatanFungsionalController@update')->name('jabatan-fungsional.update');
    Route::delete('jabatan-fungsional/{id}/delete', 'JabatanFungsionalController@delete')->name('jabatan-fungsional.destroy');
    Route::get('jabatan-fungsional', 'JabatanFungsionalController@index')->name('jabatan-fungsional.index');
    //end jabatan fungsional 

    //diklat
    Route::get('dosen/{dosen_id}/diklat', 'DiklatController@indexDosen')->name('diklat.indexDosen');
    Route::get('dosen/{dosen_id}/diklat/create', 'DiklatController@create')->name('diklat.create');
    Route::post('diklat/store', 'DiklatController@store')->name('diklat.store');
    Route::delete('diklat/{id}/delete', 'DiklatController@destroy')->name('diklat.destroy');
    Route::get('diklat/{id}/edit', 'DiklatController@edit')->name('diklat.edit');
    Route::PUT('diklat/{id}/update', 'DiklatController@update')->name('diklat.update');
    Route::get('diklat', 'DiklatController@index')->name('diklat.index');
    //end diklat

    //Penelitian pengabdian
    Route::get('dosen/{dosen_id}/penelitian-pengabdian', 'PenelitianPengabdianController@indexDosen')->name('penelitian-pengabdian.indexDosen');
    Route::get('dosen/{dosen_id}/penelitian-pengabdian/create', 'PenelitianPengabdianController@create')->name('penelitian-pengabdian.create');
    Route::post('penelitian-pengabdian/store', 'PenelitianPengabdianController@store')->name('penelitian-pengabdian.store');
    Route::delete('penelitian-pengabdian/{id}/delete', 'PenelitianPengabdianController@destroy')->name('penelitian-pengabdian.destroy');
    Route::get('penelitian-pengabdian/{id}/edit', 'PenelitianPengabdianController@edit')->name('penelitian-pengabdian.edit');
    Route::PUT('penelitian-pengabdian/{id}/update', 'PenelitianPengabdianController@update')->name('penelitian-pengabdian.update');
    Route::get('penelitian-pengabdian', 'PenelitianPengabdianController@index')->name('penelitian-pengabdian.index');
    //end penelitian pengabdian


    //pengajaran
    Route::resource('dosen/{dosen_id}/pengajaran', 'PengajaranController');
    Route::get('pengajaran', 'PengajaranController@indexAll')->name('pengajaran');
    //end pengajaran

    //sertifikasi
    Route::resource('dosen/{dosen_id}/sertifikasi', 'SertifikasiController');
    Route::get('sertifikasi', 'SertifikasiController@indexAll')->name('sertifikasi');
    //endsertifikasi

    //dosen prodi
    Route::get('prodi/{prodi_id}/dosen', 'ProdiController@dosen')->name('prodi.dosen');
    //end dosen prodi

    //dosen bidang ilmu
    Route::get('bidang-ilmu/{bidang_id}/dosen', 'BidangIlmuController@dosen')->name('bidang-ilmu.dosen');
    //end bidang ilmu

     //dosen prodi
     Route::get('almamater/{almamater_id}/dosen', 'AlmamaterController@dosen')->name('almamater.dosen');
     //end dosen prodi

     //dosen prodi
     Route::get('kompetensi/{kompetensi_id}/dosen', 'KompetensiController@dosen')->name('kompetensi.dosen');
     //end dosen prodi


     //print pdf
     Route::get('print-dosen', 'PdfController@dosen')->name('dosen.print');
     Route::get('print-dosen-prodi/{id}', 'PdfController@dosenProdi')->name('print.dosen-prodi');
     //excell
     Route::get('export-dosen', 'ExcelController@exportDosen')->name('export.dosen');
     Route::get('export-dosen-prodi/{id}', 'ExcelController@exportDosenProdi')->name('export.dosen-prodi');
});

app/Almamater.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Almamater extends Model
{
    protected $fillable = [
        'nama_almamater',
        'alamat'
    ];

    protected $table = 'almamater';

    public function dosen()
    {
        return $this->belongsTo('App\Dosen');
    }
    

}

app/Http/Controllers/AlmamaterController.php
<?php

namespace App\Http\Controllers;

use App\Almamater;
use App\Pendidikan;
use Illuminate\Http\Request;

class AlmamaterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
     public function __construct(){
        $this->middleware('kaprodi', ['only' => ['create', 'edit', 'destroy']]);
    }
    
    public function index()
    {
        return view('almamater.index')->with('almamater', Almamater::orderBy('nama_almamater')->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('almamater.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_almamater' => 'required|unique:almamater,nama_almamater',
            'alamat' => 'required'
        ]);

        Almamater::create($request->all());
        return redirect()->route('almamater.index')->with('success', 'Berhasil menambahkan data almamater');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('almamater.edit')->with('almamater', Almamater::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama_almamater' => 'required',
            'alamat' => 'required'
        ]);


        Almamater::findOrFail($id)->update($request->all());
        return redirect()->route('almamater.index')->with('success', 'Berhasil mengedit data almamater');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Almamater::findOrFail($id)->delete();
        return redirect()->route('almamater.index')->with('success', 'Berhasil menghapus data almamater');
    }

    public function dosen($id)
    {
        $pendidikan = Pendidikan::where('almamater_id', $id)->orderBy('gelar', 'asc')->get();

        $almamater = Almamater::find($id);
        return view('almamater.dosen')->with(['pendidikan' => $pendidikan, 'almamater' => $almamater]);
    }

}

resources/views/almamater/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Almamater')

@section('content')

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Tambah Almamater</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('almamater.store') }}" method="post">
                    @csrf
                    <div class="form-group">       
                        <label>Nama Almamater</label>
                        <input type="text" placeholder="contoh: Institut Teknologi dan Bisnis (ITB) STIKOM Bali" class="form-control" name="nama_almamater" value="{{ old('nama_almamater') }}">
                    </div>  
                    <div class="form-group">
                        <label>Alamat</label>
                        <textarea name="alamat" class="form-control" placeholder="Masukan Alamat">{{ old('alamat') }}</textarea>
                    </div>                    
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>                  
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/almamater/dosen.blade.php
@extends('layouts.app')

@section('title')
Dosen Almamater {{ $almamater->nama_almamater }}
@endsection


@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Dosen Pada Almamater {{ $almamater->nama_almamater }}</h4>
            </div>
            <div class="card-body mt-3">                
                <table class="table table-sm table-striped datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>NIDN</th>
                            <th>Nama</th>
                            <th>Bidang Studi</th>
                            <th>Gelar</th>
                            <th>Tahun Lulus</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($pendidikan as $row)                        
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $row->dosen->nidn }}</td>
                            <td>{{ $row->dosen->nama }}</td>
                            <td>{{ $row->bidang_studi }}</td>
                            <td>{{ $row->gelar }}</td>
                            <td>{{ $row->tahun_lulus }}</td>
                            <td>
                                <a href="{{ route('pendidikan.index', $row->dosen_id) }}" class="text-info" title="Lihat Info Dosen"><i class="fa fa-address-card"></i></a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/almamater/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Almamater')

@section('content')

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Edit Almamater</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('almamater.update', $almamater->id) }}" method="post">
                    @csrf
                    @method('put')
                    <div class="form-group">       
                        <label>Nama Almamater</label>
                        <input type="text" placeholder="contoh: Institut Teknologi dan Bisnis (ITB) STIKOM Bali" class="form-control" name="nama_almamater" value="{{ $almamater->nama_almamater }}">
                    </div>  
                    <div class="form-group">
                        <label>Alamat</label>
                        <textarea name="alamat" class="form-control" placeholder="Masukan Alamat">{{ $almamater->alamat }}</textarea>
                    </div>                    
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>                  
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/almamater/index.blade.php
@extends('layouts.app')

@section('title', 'Almamater')

@section('content')


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Almamater Dosen</h4>
            </div>
            <div class="card-body">
                <a href="{{ route('almamater.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah Almamater</a>
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Almamater</th>
                            <th>Alamat</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($almamater as $row)
                       <tr>
                           <td>{{ $loop->iteration }}</td>
                           <td>{{ $row->nama_almamater }}</td>
                           <td>{{ $row->alamat }}</td>
                           <td>
                                <form action="{{ route('almamater.destroy', $row->id) }}" method="post">
                                    <ul class="d-flex action-button">
                                        <li><a href="{{ route('almamater.dosen', $row->id) }}" class="text-primary" title="Lihat dosen dengan almamater ini"><i class="fa fa-user-tie"></i></a></li>
                                        <li><a href="{{ route('almamater.edit', $row->id) }}" class="text-secondary" title="Edit"><i class="fa fa-edit"></i></a></li>
                                        @csrf
                                        @method('delete')
                                        <!-- <li><button type="submit" class="text-danger btn-submit" onclick="return confirm('Yakin akan hapus data?')" ><i class="fa fa-trash"></i></button></li> -->
                                    </ul>
                                </form>
                           </td>
                       </tr>
                       @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection