routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});



Auth::routes();
Route::middleware('auth')->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('prodi', 'ProdiController');
    Route::resource('bidang-ilmu', 'BidangIlmuController');
    Route::resource('dosen', 'DosenController');
    Route::resource('kompetensi', 'KompetensiController');
    Route::resource('almamater', 'AlmamaterController');
    Route::resource('user', 'UserController');

    // kompetensi dosen
    Route::get('dosen/{id}/kompetensi-dosen', 'KompetensiDosenController@index')->name('kompetensi-dosen.index');
    Route::post('dosen/{id}/kompetensi-dosen', 'KompetensiDosenController@store')->name('kompetensi-dosen.store');
    Route::delete('dosen/{id}/kompetensi-dosen/{dosen_id}', 'KompetensiDosenController@delete')->name('kompetensi-dosen.destroy');
    //end kompetensi dosen

    //pendidikan dosen
    Route::get('dosen/{id}/pendidikan', 'PendidikanController@index')->name('pendidikan.index');
    Route::get('dosen/{id}/pendidikan/create', 'PendidikanController@create')->name('pendidikan.create');
    Route::post('dosen/{id}/pendidikan/create', 'PendidikanController@store')->name('pendidikan.store');
    Route::delete('dosen/{id}/pendidikan', 'PendidikanController@delete')->name('pendidikan.destroy');
    Route::get('pendidikan/{penidikan_id}/edit', 'PendidikanController@edit')->name('pendidikan.edit');
    Route::put('pendidikan/{pendidikan_id}/update', 'PendidikanController@update')->name('pendidikan.update');
    //end pendidikan dosen

    //jabatan fungsional
    Route::get('dosen/{id}/jabatan-fungsional', 'JabatanFungsionalController@indexDosen')->name('jabatan-fungsional.indexDosen');
    Route::get('dosen/{id}/jabatan-fungsional/create', 'JabatanFungsionalController@create')->name('jabatan-fungsional.create');
    Route::post('jabatan-fungsional/store', 'JabatanFungsionalController@store')->name('jabatan-fungsional.store');
    Route::get('jabatan-fungsional/{jabatan_id}/edit', 'JabatanFungsionalController@edit')->name('jabatan-fungsional.edit');
    Route::put('jabatan-fungsional/{jabatan_id}/update', 'JabatanFungsionalController@update')->name('jabatan-fungsional.update');
    Route::delete('jabatan-fungsional/{id}/delete', 'JabatanFungsionalController@delete')->name('jabatan-fungsional.destroy');
    Route::get('jabatan-fungsional', 'JabatanFungsionalController@index')->name('jabatan-fungsional.index');
    //end jabatan fungsional 

    //diklat
    Route::get('dosen/{dosen_id}/diklat', 'DiklatController@indexDosen')->name('diklat.indexDosen');
    Route::get('dosen/{dosen_id}/diklat/create', 'DiklatController@create')->name('diklat.create');
    Route::post('diklat/store', 'DiklatController@store')->name('diklat.store');
    Route::delete('diklat/{id}/delete', 'DiklatController@destroy')->name('diklat.destroy');
    Route::get('diklat/{id}/edit', 'DiklatController@edit')->name('diklat.edit');
    Route::PUT('diklat/{id}/update', 'DiklatController@update')->name('diklat.update');
    Route::get('diklat', 'DiklatController@index')->name('diklat.index');
    //end diklat

    //Penelitian pengabdian
    Route::get('dosen/{dosen_id}/penelitian-pengabdian', 'PenelitianPengabdianController@indexDosen')->name('penelitian-pengabdian.indexDosen');
    Route::get('dosen/{dosen_id}/penelitian-pengabdian/create', 'PenelitianPengabdianController@create')->name('penelitian-pengabdian.create');
    Route::post('penelitian-pengabdian/store', 'PenelitianPengabdianController@store')->name('penelitian-pengabdian.store');
    Route::delete('penelitian-pengabdian/{id}/delete', 'PenelitianPengabdianController@destroy')->name('penelitian-pengabdian.destroy');
    Route::get('penelitian-pengabdian/{id}/edit', 'PenelitianPengabdianController@edit')->name('penelitian-pengabdian.edit');
    Route::PUT('penelitian-pengabdian/{id}/update', 'PenelitianPengabdianController@update')->name('penelitian-pengabdian.update');
    Route::get('penelitian-pengabdian', 'PenelitianPengabdianController@index')->name('penelitian-pengabdian.index');
    //end penelitian pengabdian


    //pengajaran
    Route::resource('dosen/{dosen_id}/pengajaran', 'PengajaranController');
    Route::get('pengajaran', 'PengajaranController@indexAll')->name('pengajaran');
    //end pengajaran

    //sertifikasi
    Route::resource('dosen/{dosen_id}/sertifikasi', 'SertifikasiController');
    Route::get('sertifikasi', 'SertifikasiController@indexAll')->name('sertifikasi');
    //endsertifikasi

    //dosen prodi
    Route::get('prodi/{prodi_id}/dosen', 'ProdiController@dosen')->name('prodi.dosen');
    //end dosen prodi

    //dosen bidang ilmu
    Route::get('bidang-ilmu/{bidang_id}/dosen', 'BidangIlmuController@dosen')->name('bidang-ilmu.dosen');
    //end bidang ilmu

     //dosen prodi
     Route::get('almamater/{almamater_id}/dosen', 'AlmamaterController@dosen')->name('almamater.dosen');
     //end dosen prodi

     //dosen prodi
     Route::get('kompetensi/{kompetensi_id}/dosen', 'KompetensiController@dosen')->name('kompetensi.dosen');
     //end dosen prodi


     //print pdf
     Route::get('print-dosen', 'PdfController@dosen')->name('dosen.print');
     Route::get('print-dosen-prodi/{id}', 'PdfController@dosenProdi')->name('print.dosen-prodi');
     //excell
     Route::get('export-dosen', 'ExcelController@exportDosen')->name('export.dosen');
     Route::get('export-dosen-prodi/{id}', 'ExcelController@exportDosenProdi')->name('export.dosen-prodi');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password', 'dosen_id', 'level', 'status', 'username'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($val)
    {
        return $this->attributes['password'] = bcrypt($val);
    }

    public function dosen(){
        return $this->belongsTo('App\Dosen');
    }

    public function getLevel(){
        if($this->level == 1) {
            return "Admin";
        } else {
            return 'Kaprodi';
        }
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Dosen;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct(){
        $this->middleware('kaprodi', ['only' => ['create', 'edit', 'destroy']]);
    }


    public function index()
    {
        return view('user.index')->with('users', User::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['dosen'] = Dosen::all();
        return view('user.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'username' => 'required|unique:users,username',
            'password' => 'required|confirmed',
            'level' => 'required'
        ]);

        User::create($request->all());
        return redirect()->route('user.index')->with('success', 'Berhasil menambahkan data user');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('user.edit')->with('user', User::find($id))->with('dosen', Dosen::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'username' => 'required|unique:users,username,'.$id,           
            'level' => 'required',
            'password' => 'confirmed',
        ]);

        User::findOrFail($id)->update($request->all());
        return redirect()->route('user.index')->with('success', 'Berhasil mengubah data user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('title')
Tambah User
@endsection

@section('content')


<div class="row">
    <div class="col-md-7">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Tambah User</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('user.store') }}" method="post">
                    @csrf 
                    
                    <div class="form-group">       
                        <label>Username</label>
                        <input type="text" placeholder="Masukan username" class="form-control" name="username" value="{{ old('username') }}" required>
                    </div>

                    <div class="form-group">       
                        <label>Dosen <small>Kosongkan user jika bukan dosen</small></label>
                        <select name="dosen_id" class="mySelect form-control">
                            <option value=""> - Pilih Dosen - </option>
                            @foreach($dosen as $data)
                                <option value="{{ $data->id }}" {{ (old('dosen_id') == $data->id) ? 'selected' : '' }}>{{ $data->nama }}</option>                         
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">       
                        <label>Password</label>
                        <input type="password" placeholder="Masukan password" class="form-control" name="password" required>
                    </div>

                    <div class="form-group">       
                        <label>Re-type Password</label>
                        <input type="password" placeholder="Masukan password" class="form-control" name="password_confirmation" required>
                    </div>

                    <div class="form-group">       
                        <label>Level</label>
                        <select name="level" class="mySelect form-control" required>
                            <option value=""> - Pilih Level - </option>
                            <option value="1" {{ (old('level') == '1') ? 'selected' : '' }}>Admin</option>
                            <option value="0" {{ (old('level') == '0') ? 'selected' : '' }}>Kaprodi</option>
                        </select>
                    </div>

                    <div class="form-group mt-4">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div> 
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('title')
Edit User
@endsection

@section('content')


<div class="row">
    <div class="col-md-7">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Edit User</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('user.update', $user->id) }}" method="post">
                    @csrf 
                    @method('put')
                    <div class="form-group">       
                        <label>Username</label>
                        <input type="text" placeholder="Masukan username" class="form-control" name="username" value="{{ $user->username }}" required>
                    </div>

                    <div class="form-group">       
                        <label>Dosen <small>Kosongkan user jika bukan dosen</small></label>
                        <select name="dosen_id" class="mySelect form-control">
                            <option value=""> - Pilih Dosen - </option>
                            @foreach($dosen as $data)
                                <option value="{{ $data->id }}" {{ ($user->dosen_id == $data->id) ? 'selected' : '' }}>{{ $data->nama }}</option>                         
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">       
                        <label>Password</label>
                        <input type="password" placeholder="Masukan password" class="form-control" name="password">
                    </div>

                    <div class="form-group">       
                        <label>Re-type Password</label>
                        <input type="password" placeholder="Masukan password" class="form-control" name="password_confirmation">
                    </div>

                    <div class="form-group">       
                        <label>Level</label>
                        <select name="level" class="mySelect form-control" required>
                            <option value=""> - Pilih Level - </option>
                            <option value="1" {{ ($user->level == '1') ? 'selected' : '' }}>Admin</option>
                            <option value="0" {{ ($user->level == '0') ? 'selected' : '' }}>Kaprodi</option>
                        </select>
                    </div>

                    <div class="form-group mt-4">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div> 
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title')
User
@endsection

@section('content')


<div class="row">
    <div class="col-md-12">
        <div class="card">
                <div class="card-header d-flex align-items-center">
                    <h4>User </h4>
                </div>
                <div class="card-body">
                    <a href="{{ route('user.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah User</a>
                    <table class="table datatable table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Dosen</th>
                                <th>Username</th>
                                <th>Level</th>                            
                                <th>Aksi</th>
                            </tr>   
                        </thead>
                        <tbody>
                            @foreach($users as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ ($row->dosen_id != null) ? $row->dosen->nama : '' }}</td>
                                <td>{{ $row->username }}</td>
                                <td>{{ $row->getLevel() }}</td>
                                <td>
                                    <ul class="d-flex action-button">                                            
                                        <li><a href="{{ route('user.edit', $row->id) }}" class="text-secondary" title="Edit User"><i class="fa fa-edit"></i></a></li>                                            
                                    </ul>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>
        </div>
    </div>
</div>

@endsection